# Generated by Django 4.2.5 on 2023-09-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=10)),
                ('DepartmentActiveStatus', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
                ('DepartmentCreatedDate', models.DateField(null=True)),
                ('DepartmentUpdatedDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailID', models.EmailField(max_length=254)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Designation', models.CharField(max_length=20)),
                ('Role', models.CharField(choices=[('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Consultant', 'Consultant'), ('Senior Associate', 'Senior Associate'), ('Manager', 'Manager')], max_length=20)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticateApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ExpenseID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpenseDate', models.DateField()),
                ('ExpenseType', models.CharField(choices=[('Travel', 'Travel'), ('Suppplies', 'Suppplies'), ('Training', 'Training'), ('Services', 'Services')], max_length=20)),
                ('Detail', models.CharField(max_length=250)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(choices=[('Created', 'Created'), ('In Process', 'In Process'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Disputed', 'Disputed')], max_length=20)),
                ('Comments', models.TextField(max_length=250)),
                ('ApproverID', models.ForeignKey(limit_choices_to={'Role': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_approved', to='AuthenticateApp.employee')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_submitted', to='AuthenticateApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('SupportingDocuments', models.FileField(upload_to='Images/')),
                ('ExpenseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticateApp.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('DisputeID', models.AutoField(primary_key=True, serialize=False)),
                ('ReasonForDisputes', models.TextField(max_length=250)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_raised_by', to='AuthenticateApp.employee')),
                ('ExpenseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputed_expense', to='AuthenticateApp.expense')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='ManagerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerID', to='AuthenticateApp.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='ManagerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerName', to='AuthenticateApp.employee'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('Status__in', ['Created', 'In Process', 'Verified', 'Rejected', 'Disputed'])), name='valid_status_check'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('Role__in', ['Trainee', 'Associate', 'Consultant', 'Senior Associate', 'Manager'])), name='valid_role_check'),
        ),
    ]
